### ISSUE TITLE
Adding Buttons to use POS system in BTCPay 

### ISSUE THREAD

**Issue by astupidmoose** [Dogecon/siteMVP#3]
Buy Ticket buttons can be added through the use of forms. 

Here is a sample of the form which contains all dogecon ticket options which have been spec'd. 

`<form method="post" action="https://btcpay.stufftech.io/apps/7nExDVMVo6t7t6uanbdF5fQBxmDy8ZouXLtySQrsE4XX/pos">
                <div class="row">
                        <div class="col-sm-4 mb-3">
                            <h3>1 Regular Ticket</h3>
                            <button type="submit" name="choiceKey" class="btn btn-primary" value="1 Regular Ticket">Buy for $200.00</button>
                        </div>
                        <div class="col-sm-4 mb-3">
                            <h3>2 Regular Tickets</h3>
                            <button type="submit" name="choiceKey" class="btn btn-primary" value="2 Regular Tickets">Buy for $400.00</button>
                        </div>
                        <div class="col-sm-4 mb-3">
                            <h3>3 Regular Tickets</h3>
                            <button type="submit" name="choiceKey" class="btn btn-primary" value="3 Regular Tickets">Buy for $600.00</button>
                        </div>
                        <div class="col-sm-4 mb-3">
                            <h3>4 Regular Tickets</h3>
                            <button type="submit" name="choiceKey" class="btn btn-primary" value="4 Regular Tickets">Buy for $800.00</button>
                        </div>
                        <div class="col-sm-4 mb-3">
                            <h3>5 Regular Tickets</h3>
                            <button type="submit" name="choiceKey" class="btn btn-primary" value="5 Regular Tickets">Buy for $1,000.00</button>
                        </div>
                        <div class="col-sm-4 mb-3">
                            <h3>1 MAD Upgrade Ticket</h3>
                            <button type="submit" name="choiceKey" class="btn btn-primary" value="1 MAD Upgrade Ticket">Buy for $420.00</button>
                        </div>
                        <div class="col-sm-4 mb-3">
                            <h3>2 MAD Upgrade Tickets</h3>
                            <button type="submit" name="choiceKey" class="btn btn-primary" value="2 MAD Upgrade Tickets">Buy for $840.00</button>
                        </div>
                        <div class="col-sm-4 mb-3">
                            <h3>3 MAD Upgrade Tickets</h3>
                            <button type="submit" name="choiceKey" class="btn btn-primary" value="3 MAD Upgrade Tickets">Buy for $1,260.00</button>
                        </div>
                        <div class="col-sm-4 mb-3">
                            <h3>4 MAD Upgrade Tickets</h3>
                            <button type="submit" name="choiceKey" class="btn btn-primary" value="4 MAD Upgrade Tickets">Buy for $1,680.00</button>
                        </div>
                        <div class="col align-self-center">
                            <h3>5 MAD Upgrade Tickets</h3>
                            <button type="submit" name="choiceKey" class="btn btn-primary" value="5 MAD Upgrade Tickets">Buy for $2,100.00</button>
                        </div>
                </div>
            </form>`

**Comment by astupidmoose** [comment]
Sample: https://codepen.io/astupidmoose/full/NMyPXW

**Comment by please-wait** [comment]
And we are done with this too
